//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Skin.rc
//
#define IDC_SNOOZE                      2
#define IDD_ABOUTBOX2                   2
#define IDC_UPDATER_START               3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SKIN_DIALOG                 102
#define IDS_REGROOT                     102
#define IDR_MAINFRAME                   128
#define IDD_OPTIONS                     136
#define IDI_ALARM                       137
#define IDI_SKINS                       138
#define IDI_SOUNDS                      139
#define IDI_TEMPLATE                    140
#define IDI_DISPLAY                     141
#define IDI_LOCATIONS                   142
#define IDI_LOCATION                    145
#define IDI_MEMBER                      146
#define IDI_HELP                        147
#define IDI_PREFERENCES                 148
#define IDD_ALARM_MESSAGE               149
#define IDR_SYSTEMTRAY                  151
#define IDI_LOCATION_SMALL              152
#define IDD_ALARM                       220
#define IDD_LOCATIONS                   229
#define IDD_MEMBERS                     230
#define IDD_MEMBER_ADD                  231
#define IDD_PREFERENCES                 232
#define IDD_LOCATION_DETAILS            233
#define IDD_PREFERENCES_SOUNDS          234
#define IDD_PREFERENCES_TEMPLATE        235
#define IDD_PREFERENCES_MAP             236
#define IDD_PREFERENCES_TIME            237
#define IDD_PREFERENCES_LOCATIONS       238
#define IDD_PREFERENCES_LOCATIONS1      240
#define IDD_PREFERENCES_TIME1           241
#define IDD_PREFERENCES_TEMPLATE1       242
#define IDD_ALARMS                      243
#define IDD_UPDATER                     244
#define IDI_MEMBER_SMALL                279
#define IDI_UPDATER                     280
#define IDC_EDIT1                       1001
#define IDC_ALARM_APPNAME               1001
#define IDC_REGISTERED_TO               1001
#define IDC_LOC_DETAILS_NAME            1004
#define IDC_MEMBER_ADD_EMAIL            1004
#define IDC_ALARM_MESSAGE               1004
#define IDC_LOC_DETAILS_DSTOFFSET       1005
#define IDC_MEMBER_ADD_PHONE            1005
#define IDC_PREFERENCES_NIGHTSAMPLE     1005
#define IDC_LOC_DETAILS_COUNTRY         1006
#define IDC_PREFERENCES_TWILIGHTSAMPLE  1006
#define IDC_SKIN                        1007
#define IDC_ADD_HOURS                   1007
#define IDC_PREFERENCES_LISTMASKSAMPLE  1007
#define IDC_LOC_DETAILS_COUNTRYCODE     1008
#define IDC_LOC_DETAILS_DST             1009
#define IDC_CHECK1                      1009
#define IDC_ALARM_RUNAPP                1009
#define IDC_PREFERENCES_TOPMOST         1009
#define IDC_LOCATION_LIST               1010
#define IDC_LOC_DETAILS_AREACODE        1010
#define IDC_LIST                        1011
#define IDC_LOC_DETAILS_START_DAY       1011
#define IDC_LOC_DETAILS_START_FIRSTLAST 1012
#define IDC_ALARMS_ADD                  1012
#define IDC_LOC_DETAILS_START_MONTH     1013
#define IDC_ALARMS_REMOVE               1013
#define IDC_LOC_DETAILS_END_DAY         1014
#define IDC_ALARMS_PROPERTIES           1014
#define IDC_LOC_DETAILS_END_FIRSTLAST   1015
#define IDC_DATETIMEPICKER2             1015
#define IDC_ALARM_TIME                  1015
#define IDC_LOC_DETAILS_END_MONTH       1016
#define IDC_DATETIMEPICKER3             1016
#define IDC_ALARM_DATE                  1016
#define IDC_MEMBER_TOPMESSAGE           1017
#define IDC_LOC_DETAILS_LATDEGREES      1017
#define IDC_LOC_DETAILS_LATNS           1018
#define IDC_LOC_DETAILS_LONGNS          1019
#define IDC_MEMBER_ADD_NAME             1019
#define IDC_COMBO1                      1019
#define IDC_ALARM_RECURRING             1019
#define IDC_LOC_DETAILS_LONGDEGREES     1020
#define IDC_MEMBER_ADD                  1021
#define IDC_CHECK2                      1021
#define IDC_ALARM_PLAYSOUND             1021
#define IDC_MEMBER_REMOVE               1022
#define IDC_PREFERENCES_BACKGROUNDCOLOR 1022
#define IDC_MEMBER_PROPERTIES           1023
#define IDC_PROPERTIES_USETEMPLATE      1023
#define IDC_MEMBER_ADD_LOCATION         1024
#define IDC_ALARMMESSAGE                1024
#define IDC_ALARM_DETAILS               1025
#define IDC_MEMBER_LIST                 1031
#define IDC_CONNECT_STATUS              1031
#define IDC_MEMBER_ADD_LOCONLY          1032
#define IDC_PREFERENCES_SHOWAM          1038
#define IDC_PREFERENCES_24HOUR          1039
#define IDC_PREFERENCES_SECONDS         1040
#define IDC_PREFERENCES_DETAILED        1040
#define IDC_SOUNDALARM                  1046
#define IDC_SOUNDHOUR                   1047
#define IDC_TEMPLATE                    1047
#define IDC_SOUNDQUARTER                1048
#define IDC_PREFERENCES_TEMPLATEINFO    1048
#define IDC_SOUNDALARMON                1049
#define IDC_SOUNDHOURON                 1050
#define IDC_LOCATION_ADD                1051
#define IDC_SOUNDQUARTERON              1051
#define IDC_LOCATION_REMOVE             1052
#define IDC_LOCATION_PROPERTIES         1053
#define IDC_BUTTON1                     1053
#define IDC_ALARM_CHOOSEAPP             1053
#define IDC_ALARM_TEST                  1053
#define IDC_UPDATE                      1053
#define IDC_PREFERENCES_TWILIGHT        1054
#define IDC_HOUR_TEST                   1054
#define IDC_PREFERENCES_SAMPLE          1055
#define IDC_PREFERENCES_NIGHT           1055
#define IDC_QUARTER_TEST                1055
#define IDC_PREFERENCES_LISTMASK        1056
#define IDC_MESSAGE                     1061
#define IDC_ALARMSOUND_FILE             1063
#define IDC_HOURSOUND_FILE              1064
#define IDC_QUARTERSOUND_FILE           1065
#define IDC_PREFERENCES_ACTUALSIZE      1065
#define IDC_PREFERENCES_STRETCH         1066
#define IDC_PREFERENCES_USETEMPLATE     1067
#define IDC_PREFERENCES_AUTOUPDATE      1068
#define IDC_PREFERENCES_MANUALUPDATE    1069
#define IDC_PREFERENCES_UPDATEINTERVAL  1070
#define IDC_PREFERENCES_FONT            1071
#define IDC_PREFERENCES_SHOWALL         1071
#define IDC_PROPERTIES_TEMPLATE         1072
#define IDC_PREFERENCES_SHOWNIGHTMASK   1072
#define IDC_PROPERTIES_TEMPLATE2        1073
#define IDC_MEMBER_ADD_TOPMESSAGE       1074
#define IDC_PROPERTIES_TEMPLATE3        1074
#define IDC_TEMPLATE_LIST               1080
#define IDC_PREFERENCES_TRANSPARENTLOCATION 1082
#define IDC_PREFERENCES_DAY             1086
#define IDC_PREFERENCES_DAYSAMPLE       1087
#define IDC_PREFERENCES_LOCBACKGROUND   1088
#define IDC_PROPERTIES_LISTTEMPLATE     1090
#define IDC_LOCATION_LOCATIONICON       1091
#define IDC_LOCATION_PERSONICON         1092
#define ID_TRAY_RESTORE                 32773
#define ID_TRAY_OPTIONS                 32774
#define ID_TRAY_EXIT                    32775
#define ID_TRAY_ABOUT                   32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
